name: GitHub CVE234
on: [push]
jobs:
  CVETag:
    runs-on: ubuntu-latest
    if: " contains(github.event.head_commit.message, 'CVE-') "

    steps:
      - name: GET CVE
        run: |
          CVE=$( echo '${{github.event.head_commit.message}}' )
      - run: echo "CVE is $CVE"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo " commit message ${{ github.event.head_commit.message }} "
